name: Frontend Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cd:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Touch .env
        run: |
          touch ./.env
          echo "${{ secrets.KAKAO_REST_API_KEY }}" >> ./.env
          echo "${{ secrets.NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY }}" >> ./.env
          echo "${{ secrets.CLOUD_FLARE_API_KEY }}" >> ./.env
          echo "${{ secrets.CLOUD_FLARE_ACCOUNT_ID }}" >> ./.env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          ecr: auto
          logout: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_REGISTRY_URL }}:frontend
          cache-from: type=gha  # gha = Guthub Actions 용 캐시
          cache-to: type=gha,mode=max

      - name: Deploy Frontend In WEB EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.BASTION_KEY }}
          envs: GITHUB_SHA
          script: |
            ssh -i "${{ secrets.PEM_NAME }}" -o StrictHostKeyChecking=no ubuntu@${{ secrets.WEB_IP }} 'bash /home/ubuntu/frontend_deploy.sh'
